name: securepassqr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.0
  flutter_login: ^4.0.4
  responsive_builder: ^0.4.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logoqr2.png
    - assets/images/logoqr.png
    - assets/images/logoqrtipografia2.png
    - assets/images/ssssssssssssssssssssssssssssssss-removebg-preview (2).png

